//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.IronLua.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neo.IronLua.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conversion defined from {0} to {1}..
        /// </summary>
        internal static string rsBindConversionNotDefined {
            get {
                return ResourceManager.GetString("rsBindConversionNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No operator is defined for {1} {0} {2}..
        /// </summary>
        internal static string rsBindOperatorNotDefined {
            get {
                return ResourceManager.GetString("rsBindOperatorNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunk is not compiled..
        /// </summary>
        internal static string rsChunkNotCompiled {
            get {
                return ResourceManager.GetString("rsChunkNotCompiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No type for the generic argument {0}..
        /// </summary>
        internal static string rsClrGenericNoType {
            get {
                return ResourceManager.GetString("rsClrGenericNoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clr type expected..
        /// </summary>
        internal static string rsClrGenericTypeExpected {
            get {
                return ResourceManager.GetString("rsClrGenericTypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant expression could not evaluate ({0})..
        /// </summary>
        internal static string rsConstExpressionEvalError {
            get {
                return ResourceManager.GetString("rsConstExpressionEvalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant expression expected..
        /// </summary>
        internal static string rsConstExpressionNeeded {
            get {
                return ResourceManager.GetString("rsConstExpressionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument ar must from the same LuaThread..
        /// </summary>
        internal static string rsCoroutineInvalidAR {
            get {
                return ResourceManager.GetString("rsCoroutineInvalidAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument co must be a LuaThread or a Thread..
        /// </summary>
        internal static string rsCoroutineInvalidCO {
            get {
                return ResourceManager.GetString("rsCoroutineInvalidCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeginResume is not called..
        /// </summary>
        internal static string rsCoroutineNoBeginResume {
            get {
                return ResourceManager.GetString("rsCoroutineNoBeginResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yield from wrong thread..
        /// </summary>
        internal static string rsCoroutineWrongThread {
            get {
                return ResourceManager.GetString("rsCoroutineWrongThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate must not have out parameters..
        /// </summary>
        internal static string rsDelegateCouldNotHaveOut {
            get {
                return ResourceManager.GetString("rsDelegateCouldNotHaveOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression is not enumerable..
        /// </summary>
        internal static string rsExpressionNotEnumerable {
            get {
                return ResourceManager.GetString("rsExpressionNotEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mode format..
        /// </summary>
        internal static string rsFileInvalidModeFormat {
            get {
                return ResourceManager.GetString("rsFileInvalidModeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not read from file..
        /// </summary>
        internal static string rsFileNotReadable {
            get {
                return ResourceManager.GetString("rsFileNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File pointer can not set to a new position..
        /// </summary>
        internal static string rsFileNotSeekable {
            get {
                return ResourceManager.GetString("rsFileNotSeekable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not write into file..
        /// </summary>
        internal static string rsFileNotWriteable {
            get {
                return ResourceManager.GetString("rsFileNotWriteable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not format &apos;{0}&apos; to {1}..
        /// </summary>
        internal static string rsFormatError {
            get {
                return ResourceManager.GetString("rsFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; on type &apos;{1}&apos; already exists..
        /// </summary>
        internal static string rsGlobalFunctionNotUnique {
            get {
                return ResourceManager.GetString("rsGlobalFunctionNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No index found for type &apos;{0}&apos;..
        /// </summary>
        internal static string rsIndexNotFound {
            get {
                return ResourceManager.GetString("rsIndexNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not callable..
        /// </summary>
        internal static string rsInvokeNoDelegate {
            get {
                return ResourceManager.GetString("rsInvokeNoDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}:{1}&apos; is not readable..
        /// </summary>
        internal static string rsMemberNotReadable {
            get {
                return ResourceManager.GetString("rsMemberNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}:{1}&apos; not found..
        /// </summary>
        internal static string rsMemberNotResolved {
            get {
                return ResourceManager.GetString("rsMemberNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}:{1}&apos; must be unique..
        /// </summary>
        internal static string rsMemberNotUnique {
            get {
                return ResourceManager.GetString("rsMemberNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}:{1}&apos; is not writable..
        /// </summary>
        internal static string rsMemberNotWritable {
            get {
                return ResourceManager.GetString("rsMemberNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not mix static and non-static methods ({0})..
        /// </summary>
        internal static string rsMethodStaticMix {
            get {
                return ResourceManager.GetString("rsMethodStaticMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not call nil value..
        /// </summary>
        internal static string rsNilNotCallable {
            get {
                return ResourceManager.GetString("rsNilNotCallable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator is not defined for nil-values..
        /// </summary>
        internal static string rsNilOperatorError {
            get {
                return ResourceManager.GetString("rsNilOperatorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No length for {0}..
        /// </summary>
        internal static string rsNoLengthOperator {
            get {
                return ResourceManager.GetString("rsNoLengthOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is nil..
        /// </summary>
        internal static string rsNullReference {
            get {
                return ResourceManager.GetString("rsNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number expected..
        /// </summary>
        internal static string rsNumberExpected {
            get {
                return ResourceManager.GetString("rsNumberExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment expected..
        /// </summary>
        internal static string rsParseAssignmentExpected {
            get {
                return ResourceManager.GetString("rsParseAssignmentExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument type must be assignable to Exception (unexpected type: {0}).
        /// </summary>
        internal static string rsParseCatchVarTypeMustAssignableToException {
            get {
                return ResourceManager.GetString("rsParseCatchVarTypeMustAssignableToException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number expected (&apos;{0}&apos; not converted)..
        /// </summary>
        internal static string rsParseConvertNumberError {
            get {
                return ResourceManager.GetString("rsParseConvertNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current block is closed before end of file..
        /// </summary>
        internal static string rsParseEof {
            get {
                return ResourceManager.GetString("rsParseEof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression has no result..
        /// </summary>
        internal static string rsParseExpressionNoResult {
            get {
                return ResourceManager.GetString("rsParseExpressionNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression is not assignable..
        /// </summary>
        internal static string rsParseExpressionNotAssignable {
            get {
                return ResourceManager.GetString("rsParseExpressionNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named arguments specifications must appear after all fixed arguments have been specified..
        /// </summary>
        internal static string rsParseInvalidArgList {
            get {
                return ResourceManager.GetString("rsParseInvalidArgList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected char..
        /// </summary>
        internal static string rsParseInvalidChar {
            get {
                return ResourceManager.GetString("rsParseInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment not closed..
        /// </summary>
        internal static string rsParseInvalidComment {
            get {
                return ResourceManager.GetString("rsParseInvalidComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewLine in string constant..
        /// </summary>
        internal static string rsParseInvalidString {
            get {
                return ResourceManager.GetString("rsParseInvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid long string delimiter..
        /// </summary>
        internal static string rsParseInvalidStringOpening {
            get {
                return ResourceManager.GetString("rsParseInvalidStringOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No arglist defined..
        /// </summary>
        internal static string rsParseNoArgList {
            get {
                return ResourceManager.GetString("rsParseNoArgList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not allowed to redefine the type..
        /// </summary>
        internal static string rsParseTypeRedef {
            get {
                return ResourceManager.GetString("rsParseTypeRedef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token &apos;{0}&apos;. &apos;{1}&apos; expected..
        /// </summary>
        internal static string rsParseUnexpectedToken {
            get {
                return ResourceManager.GetString("rsParseUnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token in Else-Statement.
        /// </summary>
        internal static string rsParseUnexpectedTokenElse {
            get {
                return ResourceManager.GetString("rsParseUnexpectedTokenElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literal, function or table-ctor expected..
        /// </summary>
        internal static string rsParseUnexpectedTokenPrefix {
            get {
                return ResourceManager.GetString("rsParseUnexpectedTokenPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; not found..
        /// </summary>
        internal static string rsParseUnknownType {
            get {
                return ResourceManager.GetString("rsParseUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  at .
        /// </summary>
        internal static string rsStackTraceAt {
            get {
                return ResourceManager.GetString("rsStackTraceAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -- internal --.
        /// </summary>
        internal static string rsStackTraceInternal {
            get {
                return ResourceManager.GetString("rsStackTraceInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  line .
        /// </summary>
        internal static string rsStackTraceLine {
            get {
                return ResourceManager.GetString("rsStackTraceLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;unknown method&gt;.
        /// </summary>
        internal static string rsStackTraceUnknownMethod {
            get {
                return ResourceManager.GetString("rsStackTraceUnknownMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a value with the key &apos;{0}&apos;..
        /// </summary>
        internal static string rsTableAddDuplicate {
            get {
                return ResourceManager.GetString("rsTableAddDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to call &apos;{0}&apos;..
        /// </summary>
        internal static string rsTableCallMemberFailed {
            get {
                return ResourceManager.GetString("rsTableCallMemberFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nil is not a valid key..
        /// </summary>
        internal static string rsTableKeyNotNullable {
            get {
                return ResourceManager.GetString("rsTableKeyNotNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods must have a LuaTable as first parameter (&apos;{0}&apos;)..
        /// </summary>
        internal static string rsTableMethodExpected {
            get {
                return ResourceManager.GetString("rsTableMethodExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; is not compatible (expected {1})..
        /// </summary>
        internal static string rsTableOperatorIncompatible {
            get {
                return ResourceManager.GetString("rsTableOperatorIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; is not defined for the table..
        /// </summary>
        internal static string rsTableOperatorNotFound {
            get {
                return ResourceManager.GetString("rsTableOperatorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursion level is to deep..
        /// </summary>
        internal static string rsTableRecursionLevelError {
            get {
                return ResourceManager.GetString("rsTableRecursionLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name for type alias is invalid &apos;{0}&apos;..
        /// </summary>
        internal static string rsTypeAliasInvalidName {
            get {
                return ResourceManager.GetString("rsTypeAliasInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0}.{1} must be static, public and needs at least one parameter..
        /// </summary>
        internal static string rsTypeExtentionInvalidMethod {
            get {
                return ResourceManager.GetString("rsTypeExtentionInvalidMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not static..
        /// </summary>
        internal static string rsTypeExtentionInvalidType {
            get {
                return ResourceManager.GetString("rsTypeExtentionInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a pointer or byref type. These types can not converted to a LuaType..
        /// </summary>
        internal static string rsTypeInvalidType {
            get {
                return ResourceManager.GetString("rsTypeInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &quot;{0}&quot; is not supported..
        /// </summary>
        internal static string rsTypeIsNotSupported {
            get {
                return ResourceManager.GetString("rsTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type format for &apos;{0}&apos; (unexpected: {1} at {2}; expected: {3}).
        /// </summary>
        internal static string rsTypeParseError {
            get {
                return ResourceManager.GetString("rsTypeParseError", resourceCulture);
            }
        }
    }
}
