//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.IronLua.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neo.IronLua.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No conversion defined from {0} to {1}. ähnelt.
        /// </summary>
        internal static string rsBindConversionNotDefined {
            get {
                return ResourceManager.GetString("rsBindConversionNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No operator is defined for {1} {0} {2}. ähnelt.
        /// </summary>
        internal static string rsBindOperatorNotDefined {
            get {
                return ResourceManager.GetString("rsBindOperatorNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chunk is not compiled. ähnelt.
        /// </summary>
        internal static string rsChunkNotCompiled {
            get {
                return ResourceManager.GetString("rsChunkNotCompiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chunk is compiled in a differend script-manager. ähnelt.
        /// </summary>
        internal static string rsChunkWrongScriptManager {
            get {
                return ResourceManager.GetString("rsChunkWrongScriptManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No type for the generic argument {0}. ähnelt.
        /// </summary>
        internal static string rsClrGenericNoType {
            get {
                return ResourceManager.GetString("rsClrGenericNoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clr type expected. ähnelt.
        /// </summary>
        internal static string rsClrGenericTypeExpected {
            get {
                return ResourceManager.GetString("rsClrGenericTypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Constant expression could not evaluate ({0}). ähnelt.
        /// </summary>
        internal static string rsConstExpressionEvalError {
            get {
                return ResourceManager.GetString("rsConstExpressionEvalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Constant expression expected. ähnelt.
        /// </summary>
        internal static string rsConstExpressionNeeded {
            get {
                return ResourceManager.GetString("rsConstExpressionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Argument ar must from the same LuaThread. ähnelt.
        /// </summary>
        internal static string rsCoroutineInvalidAR {
            get {
                return ResourceManager.GetString("rsCoroutineInvalidAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Argument co must be a LuaThread or a Thread. ähnelt.
        /// </summary>
        internal static string rsCoroutineInvalidCO {
            get {
                return ResourceManager.GetString("rsCoroutineInvalidCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BeginResume is not called. ähnelt.
        /// </summary>
        internal static string rsCoroutineNoBeginResume {
            get {
                return ResourceManager.GetString("rsCoroutineNoBeginResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yield from wrong thread. ähnelt.
        /// </summary>
        internal static string rsCoroutineWrongThread {
            get {
                return ResourceManager.GetString("rsCoroutineWrongThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delegate must not have out parameters. ähnelt.
        /// </summary>
        internal static string rsDelegateCouldNotHaveOut {
            get {
                return ResourceManager.GetString("rsDelegateCouldNotHaveOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expression is not enumerable. ähnelt.
        /// </summary>
        internal static string rsExpressionNotEnumerable {
            get {
                return ResourceManager.GetString("rsExpressionNotEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid mode format. ähnelt.
        /// </summary>
        internal static string rsFileInvalidModeFormat {
            get {
                return ResourceManager.GetString("rsFileInvalidModeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can not read from file. ähnelt.
        /// </summary>
        internal static string rsFileNotReadable {
            get {
                return ResourceManager.GetString("rsFileNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File pointer can not set to a new position. ähnelt.
        /// </summary>
        internal static string rsFileNotSeekable {
            get {
                return ResourceManager.GetString("rsFileNotSeekable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can not write into file. ähnelt.
        /// </summary>
        internal static string rsFileNotWriteable {
            get {
                return ResourceManager.GetString("rsFileNotWriteable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can not format &apos;{0}&apos; to {1}. ähnelt.
        /// </summary>
        internal static string rsFormatError {
            get {
                return ResourceManager.GetString("rsFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Function &apos;{0}&apos; on type &apos;{1}&apos; already exists. ähnelt.
        /// </summary>
        internal static string rsGlobalFunctionNotUnique {
            get {
                return ResourceManager.GetString("rsGlobalFunctionNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No index found for type &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string rsIndexNotFound {
            get {
                return ResourceManager.GetString("rsIndexNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type &apos;{0}&apos; is not callable. ähnelt.
        /// </summary>
        internal static string rsInvokeNoDelegate {
            get {
                return ResourceManager.GetString("rsInvokeNoDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}:{1}&apos; is not readable. ähnelt.
        /// </summary>
        internal static string rsMemberNotReadable {
            get {
                return ResourceManager.GetString("rsMemberNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}:{1}&apos; not found. ähnelt.
        /// </summary>
        internal static string rsMemberNotResolved {
            get {
                return ResourceManager.GetString("rsMemberNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}:{1}&apos; must be unique. ähnelt.
        /// </summary>
        internal static string rsMemberNotUnique {
            get {
                return ResourceManager.GetString("rsMemberNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}:{1}&apos; is not writable. ähnelt.
        /// </summary>
        internal static string rsMemberNotWritable {
            get {
                return ResourceManager.GetString("rsMemberNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can not call nil value. ähnelt.
        /// </summary>
        internal static string rsNilNotCallable {
            get {
                return ResourceManager.GetString("rsNilNotCallable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operator is not defined for nil-values. ähnelt.
        /// </summary>
        internal static string rsNilOperatorError {
            get {
                return ResourceManager.GetString("rsNilOperatorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Object is nil. ähnelt.
        /// </summary>
        internal static string rsNullReference {
            get {
                return ResourceManager.GetString("rsNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number expected. ähnelt.
        /// </summary>
        internal static string rsNumberExpected {
            get {
                return ResourceManager.GetString("rsNumberExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assignment expected. ähnelt.
        /// </summary>
        internal static string rsParseAssignmentExpected {
            get {
                return ResourceManager.GetString("rsParseAssignmentExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number expected (&apos;{0}&apos; not converted). ähnelt.
        /// </summary>
        internal static string rsParseConvertNumberError {
            get {
                return ResourceManager.GetString("rsParseConvertNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current block is closed before end of file. ähnelt.
        /// </summary>
        internal static string rsParseEof {
            get {
                return ResourceManager.GetString("rsParseEof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expression has no result. ähnelt.
        /// </summary>
        internal static string rsParseExpressionNoResult {
            get {
                return ResourceManager.GetString("rsParseExpressionNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expression is not assignable. ähnelt.
        /// </summary>
        internal static string rsParseExpressionNotAssignable {
            get {
                return ResourceManager.GetString("rsParseExpressionNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected char. ähnelt.
        /// </summary>
        internal static string rsParseInvalidChar {
            get {
                return ResourceManager.GetString("rsParseInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comment not closed. ähnelt.
        /// </summary>
        internal static string rsParseInvalidComment {
            get {
                return ResourceManager.GetString("rsParseInvalidComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NewLine in string constant. ähnelt.
        /// </summary>
        internal static string rsParseInvalidString {
            get {
                return ResourceManager.GetString("rsParseInvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No arglist defined. ähnelt.
        /// </summary>
        internal static string rsParseNoArgList {
            get {
                return ResourceManager.GetString("rsParseNoArgList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It is not allowed to redefine the type. ähnelt.
        /// </summary>
        internal static string rsParseTypeRedef {
            get {
                return ResourceManager.GetString("rsParseTypeRedef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected token &apos;{0}&apos;. &apos;{1}&apos; expected. ähnelt.
        /// </summary>
        internal static string rsParseUnexpectedToken {
            get {
                return ResourceManager.GetString("rsParseUnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected token in Else-Statement ähnelt.
        /// </summary>
        internal static string rsParseUnexpectedTokenElse {
            get {
                return ResourceManager.GetString("rsParseUnexpectedTokenElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Literal, function or tablector expected. ähnelt.
        /// </summary>
        internal static string rsParseUnexpectedTokenPrefix {
            get {
                return ResourceManager.GetString("rsParseUnexpectedTokenPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type &apos;{0}&apos; not found. ähnelt.
        /// </summary>
        internal static string rsParseUnknownType {
            get {
                return ResourceManager.GetString("rsParseUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  at  ähnelt.
        /// </summary>
        internal static string rsStackTraceAt {
            get {
                return ResourceManager.GetString("rsStackTraceAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  -- internal -- ähnelt.
        /// </summary>
        internal static string rsStackTraceInternal {
            get {
                return ResourceManager.GetString("rsStackTraceInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  line  ähnelt.
        /// </summary>
        internal static string rsStackTraceLine {
            get {
                return ResourceManager.GetString("rsStackTraceLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;unknown method&gt; ähnelt.
        /// </summary>
        internal static string rsStackTraceUnknownMethod {
            get {
                return ResourceManager.GetString("rsStackTraceUnknownMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operator &apos;{0}&apos; is not compatible (expected {1}). ähnelt.
        /// </summary>
        internal static string rsTableOperatorIncompatible {
            get {
                return ResourceManager.GetString("rsTableOperatorIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operator &apos;{0}&apos; is not defined for the table. ähnelt.
        /// </summary>
        internal static string rsTableOperatorNotFound {
            get {
                return ResourceManager.GetString("rsTableOperatorNotFound", resourceCulture);
            }
        }
    }
}
